### ISSUE TITLE
Plugin selector web app is down

### ISSUE THREAD

**Issue by Trosterud** [swc-project/website#276]
On plugins.swc.rs, after loading the only shows: 
`Application error: a client-side exception has occurred (see the browser console for more information).`

The console logs:

```Failed to load resource: the server responded with a status of 500 ()
677-4f3bb3bb36200f07.js:6 
        
        
       GET https://plugins.swc.rs/api/trpc/runtime.list?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 500 (Internal Server Error)
E @ 677-4f3bb3bb36200f07.js:6
await in E
C @ 677-4f3bb3bb36200f07.js:6
w @ 677-4f3bb3bb36200f07.js:6
fetch @ 677-4f3bb3bb36200f07.js:6
i @ 677-4f3bb3bb36200f07.js:6
setTimeout
load @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
subscribe @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
subscribe @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
subscribe @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
requestAsPromise @ 677-4f3bb3bb36200f07.js:6
query @ 677-4f3bb3bb36200f07.js:6
queryFn @ 677-4f3bb3bb36200f07.js:6
fetchFn @ 677-4f3bb3bb36200f07.js:6
g @ 677-4f3bb3bb36200f07.js:6
(anonymous) @ 677-4f3bb3bb36200f07.js:6
410-886576af96fce7d5.js:1 TRPCClientError: 
Invalid `prisma.swcRuntime.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at u.from (677-4f3bb3bb36200f07.js:6:25205)
    at 677-4f3bb3bb36200f07.js:6:31689```

**Comment by kdy1** [comment]
Fixed it
